---
title: "Group Expectations and Code of Conduct"
format:
  html:
    template-partials:
      - partials/title_only/title-block.html
---

This document lays out our group's rules and code of conduct. It aims to clarify and manage expectations very early on in our work together. It is a living document and gets updated based on situations and discussions we have along the way.

::: {.callout-note title="Note" appearance="simple"}
I am always open to discuss individual or missing points and happy to adjust this document accordingly.
:::

::: {.callout-note title="Social Activities" appearance="simple"}
One of the benefits of joining our group is that we also like to have other types of fun (not related to science or research)
and we post the pictures of our gatherings [here](/content/fun.html).
:::

## Ground rules

-   We judge each other based on our character and behavior and treat each other with respect.
-   This group's hierarchy is very flat (which is more common in the US than some other countries). Our respect for one another, does not depend on our professional qualifications and we stand on equal footing.
-   Research and academia is about critical thinking. In our day-to-day work we have to criticize and question each other constantly - however, this is purely related to research and does not relate to any personal qualities. Criticism is always to be stated and assumed to be **in good faith**. Especially in written communication, criticism can sound more personal than it was actually meant. Always assume written communication was meant in good faith. _Personal attacks are not tolerated_.
-   *"I don't know"* is a perfectly reasonable answer. Academia is about integrity and learning, it's not about knowing everything.
-   We welcome people from all backgrounds, races, genders, religions, and cultures. We all have biases and as a lab with many international people we all have different cultural backgrounds. However, we aim to tackle the biases we (unconsciously) hold and help each other to understand each other's viewpoints and point us to our own blind spots.
-   Mistakes happen and conflict can arise. Always try to address these issues shortly after they arose in a 1-on-1 conversation (ideally in person). Don't ignore issues and let them bottle up or act in a passive aggressive way. If the 1-on-1 meeting did not solve the issue, involve me in the meeting and I can try to mediate. If I am the person who you have an issue with, also talk to me 1-on-1 first. If that does not resolve the issue, reach out to the Department chair or any relevant advisor at Northeastern.
-   In general, I am always happy to meet with anyone from the group (regardless if active or past member) to give life advice and try my best to help you succeed and overcome life challenges. You can share everything in confidence with me - however, be aware that I am _obligated to report certain information_ if that information falls under [Title IX](https://www.northeastern.edu/ouec/).

## My General Expectations

The following points do not apply for co-advised students as their work agreement is with their main advisor, not with me.

-   I am giving you freedom on how/when to work. You have to figure out what works best for you and which way you are most productive (e.g. I am quite productive at night - but that doesn't mean you need to reply to my emails at midnight). I won't be micro-managing you.
-   The main thing I expect of you is scientific curiosity, that you are driven to learn something new, and grow as a person/professional.
-   Academia is about endurance and learning. So, try to not burn yourself out - research is more like a marathon, not a sprint. Focus on working smart rather than hard. Take breaks when you need them! Our work involves a lot of creativity and focus - it's hard to be truly creative when stressed.
-   The number of hours spent on research depend on your position/employment and our arrangement. Details are discussed in the next section. Typically, I don't expect you to work on weekends and holidays and I avoid having meetings scheduled outside of 9 am - 5 pm EST. In rare circumstances (e.g. close to some deadline or due to time zone shifts) there may be an exception to this but should generally not be expected. However, from my own experience as a Ph.D. student, I know there are phases (e.g. exams week) where things can get crazy. I aim to support you during those times as much as I can.
-   Physical and mental health goes first. If you need a day off for these reasons, that is perfectly fine with me and does not count as vacation days.
-   Discuss longer leaves of absence and vacation ahead of time with me. This is mainly for planning purposes.
-   We typically take time off during winter break (at the very least no meetings) and about 2 weeks during the summer (some meetings might be virtual when I am traveling).

## What You Can Expect of Me

-   You can consider me your supporter, cheerleader, and friend. However, an annoying kind of friend, that always wants you to be the best version of yourself and pushes you to improve.
-   My main aim is to enable you to be successful in your career and enjoy the path towards your goals. For that I will help you with career advice, resume/CV critique, connect you to opportunities in academia, industry, and start-ups. Having spent time in both academia and start-ups working with industrial partners gives me a wide perspective and I'm able to advise you on various career trajectories.
-   Advice and training in various soft skills and skills relevant in academia and industry, such as presentation skills, scientific writing, software engineering, coding, networking, etc.
-   **Recommendation letter**:<br>
    If we work together for at least 10 hours a week for 1 semester, then I can typically judge your performance enough to be able to write you a recommendation letter. Your input and progress during our time working together determines the strength of that letter. Please, inform me a few weeks ahead of time and share with me your updated CV, job posting, and relevant talking points that help me to write the letter.

## Communication and Meetings

-   You can call me *"Professor"*, *"Prof. Peter"* or *"Dr. Peter"*.
-   Let me know about your food restrictions, customs, religious holidays that you observe or anything else that may help me adjust to your needs.
-   Daily communication is preferred via Teams. For longer issues (and administrative issues that involve MIE/NEU staff) email is preferable. For very urgent matters you can text my cell, but I typically receive Teams notifications on my phone anyway.
-   Ideally, reply to my messages on the same day or the next. I will try to hold myself accountable to the same standard. The reply can also be just "_I am currently busy doing X, I will get back to you on Y_".

## Publications and Authorship

-   Authorship on publications should be discussed as soon as reasonably possible. The role, order, and involvement of authors should be clarified.
-   Usually, it is clear who is the lead author (if not, discuss with me) and the lead author is in charge of having the authorship discussion early and openly.
-   Utilize the [CRediT](https://authorservices.wiley.com/author-resources/Journal-Authors/open-access/credit.html) system to assign and determine author contributions. We aim to always include a dedicated paragraph at the end of publications using the CRediT system.

## My *Specific* Expectations of You as a...

-   **Post-doctoral Researcher/Scholar or Visiting Scholar**
    -   You are already an independent researcher 😄 Hence, we are working together similar to scientific collaborators. You have skills I don't have and I have skills that you don't have. I will still advise you on the general direction of our projects together and also help you plan for your next career steps.
    -   You will be expected to advise graduate and undergraduate students in our group and help them getting up to speed with various computational topics.
    -   You will have opportunities to support me during teaching (especially critical if you want to pursue an academic career).
    -   Overall I give you a lot of freedom in pursuing your research interests (especially if you have your own funding/scholarship). However, I do expect some contribution to the group's code base and development of computational workflows that benefit the entire group's research activities. If you are hired for a specific externally funded project, then you are of course in charge of it.
-   **Ph.D. Student/Candidate**
    -   The Ph.D. is a marathon and I am here to support you along the way.
    -   I closely advise you on research and career development. In the beginning I will tell you what to focus on and in our discussions I will mostly know the answers to problems. As you progress during your Ph.D. my involvement as an advisor steadily decreases and by the end of it you will know the answers and I won't. That evolution will be exciting to see unfold!
    -   Research and fulfilling your course credits will be a full-time job. Typically, during the summer you can focus entirely on research.
    -   The courses you pick ideally complement the research that you do for your thesis (while also covering all core materials science courses).
    -   I generally advise doing an internship towards the later stages of your PhD (end of 3<sup>rd</sup> year) and I will help you with the search. Ideally, that internship complements your research expertise (while enhancing it).
-   **Master's and Undergraduate Students**
    -   The project we work on together is usually clearly defined and the scope and effort per week for a certain duration is agreed upon in our initial meeting.
    -   A reasonable research project usually is a commitment of at least 10 hours/week for at least 1 semester. This is also the typical minimum to justify a recommendation letter (depending on your performance). Two semesters is typically better to finalize meaningful work and potentially publish the results.
    -   I advise the necessary steps during most of the project but I am happy to see self-guided initiative as well.
    -   I support you and provide you guidance on next career steps.

