---
title: "Open Positions"
format:
  html:
    template-partials:
      - partials/title_only/title-block.html
aliases:
  - ../join/
---
## Doctoral and Postdoctoral Positions

These are the current (fully funded) positions at the D2R2 group at Northeastern University:

- 1 Postdoctoral Research Associate (Summer/Fall 2024) -- Apply [here](https://northeastern.wd1.myworkdayjobs.com/careers/job/Boston-MA-Main-Campus/Postdoctoral-Research-Associate_R120912)
- ~~1 Graduate Research Assistant (Fall 2024)~~ [filled]
- ~~1 Graduate Research Assistant (Fall 2023)~~ [filled]
- ~~1 Postdoctoral Researcher (Spring 2023)~~ [filled]

Details for the **postdoctoral research associate** position in our group are described in the flyer below.<br>
If this sounds interesting to you, please apply [here](https://northeastern.wd1.myworkdayjobs.com/careers/job/Boston-MA-Main-Campus/Postdoctoral-Research-Associate_R120912) and email me your CV.

{{< pdf ../images/group/D2R2group_Postdoc_Position_Fall2023.pdf width=80% height=800 >}}

Regardless of open positions, feel free to reach out to me to discuss potential future opportunities.<br>

Our research is focused on the discovery of novel materials for renewable energy applications using high-throughput,
*ab-initio* calculations, and data-driven materials property predictions.
Further information on our research can be found [here](../research/).<br>

> If your background is in computational materials science (or computational chemistry, solid state physics,
> or similar field) and you are interested in the research described above, please send me an email with your CV and
> brief description of your background and research interests.

::: {.callout-note title="Graduate Admissions" appearance="simple"}
Information regarding graduate admissions can be found [here](https://coe.northeastern.edu/academics-experiential-learning/graduate-school-of-engineering/graduate-admissions/)
and some facts about graduate research at *College of Engineering* can be read [here](https://coe.northeastern.edu/academics-experiential-learning/graduate-school-of-engineering/) and
[here](https://coe.northeastern.edu/wp-content/uploads/pdfs/coe/gse/graduate_brochure.pdf).
:::

## Undergraduate Projects and Master's Thesis

Undergraduate students from Northeastern University interested in computational chemistry or materials
informatics/machine learning are always welcome to contact me and we can establish undergraduate research projects
or Master's thesis under my supervision.<br>
**Funding opportunities available.** Minimum time commitment: 10 hours/week for ~6 months.

## Co-Ops and Internships

I have strong connections to start-ups in the renewable energy sector and materials informatics and I can help to
connect (under)graduates to Co-Op or internship opportunities. Reach out if that sounds interesting to you.

## Visiting Researchers and Fellows

Visiting researchers and researchers with a fellowship are always welcome to reach out to me to discuss the
opportunity to work on a project together.<br>
*International applicants*: J1 visa processing typically takes 3-6 months.
Further information can be found [here](https://international.northeastern.edu/ogs/).